from pathlib import Path
import sys

from fontTools import subset
from fontTools.ttLib import TTFont


ROOT = Path(__file__).resolve().parents[1]
FONT_DIR = ROOT / "public" / "fonts" / "source-han-sans"
SOURCE = FONT_DIR / "SourceHanSansSC-VF.ttf.woff2"
CSS_OUTPUT = ROOT / "src" / "source-han-sans.css"

BASE_RANGES = (
    (0x0000, 0x024F),
    (0x2000, 0x206F),
    (0x20A0, 0x20CF),
    (0x2100, 0x214F),
    (0x2190, 0x22FF),
    (0x2460, 0x27BF),
    (0x2E80, 0x2EFF),
    (0x3000, 0x303F),
    (0xFE10, 0xFE6F),
    (0xFF00, 0xFFEF),
)


def compact_ranges(codepoints):
    values = sorted(codepoints)
    if not values:
        return []
    ranges = []
    start = previous = values[0]
    for value in values[1:]:
        if value != previous + 1:
            ranges.append((start, previous))
            start = value
        previous = value
    ranges.append((start, previous))
    return ranges


def unicode_spec(codepoints):
    return ",".join(
        f"U+{start:X}" if start == end else f"U+{start:X}-{end:X}"
        for start, end in compact_ranges(codepoints)
    )


def gb2312_codepoints():
    result = set()
    for high in range(0xA1, 0xF8):
        for low in range(0xA1, 0xFF):
            try:
                result.add(ord(bytes((high, low)).decode("gb2312")))
            except UnicodeDecodeError:
                pass
    return result


def subset_font(name, codepoints):
    target = FONT_DIR / f"SourceHanSansSC-VF-{name}.woff2"
    subset.main(
        [
            str(SOURCE),
            f"--output-file={target}",
            f"--unicodes={unicode_spec(codepoints)}",
            "--flavor=woff2",
            "--layout-features=*",
            "--no-hinting",
            "--drop-tables+=DSIG",
        ]
    )
    return target


def face(filename, codepoints):
    ranges = unicode_spec(codepoints).replace(",", ",\n    ")
    return f"""@font-face{{
  font-family:'Source Han Sans SC VF';
  src:url('/fonts/source-han-sans/{filename}') format('woff2');
  font-style:normal;
  font-weight:200 900;
  font-display:swap;
  unicode-range:{ranges};
}}"""


def main():
    force = "--force" in sys.argv
    font = TTFont(SOURCE)
    available = set(font.getBestCmap())
    font.close()

    base = {
        codepoint
        for start, end in BASE_RANGES
        for codepoint in range(start, end + 1)
        if codepoint in available
    }
    common = (gb2312_codepoints() & available) - base
    extended = available - base - common
    assert not (base & common or base & extended or common & extended)
    assert base | common | extended == available

    subsets = (("base", base), ("common", common))
    for name, codepoints in subsets:
        target = FONT_DIR / f"SourceHanSansSC-VF-{name}.woff2"
        if force or not target.exists():
            target = subset_font(name, codepoints)
        print(f"{name}: {len(codepoints)} glyph mappings, {target.stat().st_size} bytes")

    faces = (
        ("SourceHanSansSC-VF-base.woff2", base),
        ("SourceHanSansSC-VF-common.woff2", common),
        ("SourceHanSansSC-VF.ttf.woff2", extended),
    )
    CSS_OUTPUT.write_text(
        "/* Generated by scripts/subset-source-han.py. */\n"
        + "\n".join(face(filename, codepoints) for filename, codepoints in faces)
        + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
