import React, { useRef, useState } from 'react'
import { ArrowUp, AtSign, Bot, Check, ChevronDown, Code2, FileText, GalleryHorizontalEnd, Image, Paperclip, Play, Plus, Sparkles, Square, X } from 'lucide-react'
import './prompt-states.css'

const modes=[['agent',Bot,'Agent'],['image',Image,'图片生成'],['video',GalleryHorizontalEnd,'视频生成']]
const models={agent:['Opus 4.6','Sonnet 4.5','ShuLan 快速版'],image:['Image 5.0 Lite','Image Pro','ShuLan Canvas'],video:['Video Flow 2.1','Video Pro','ShuLan Motion']}
const placeholders={agent:'输入任务，或继续追问…',image:'描述画面、风格、构图和尺寸…',video:'描述镜头、运动、时长和画面风格…'}
const initialFiles=[{name:'产品主视觉.jpg',kind:'image'},{name:'品牌短片.mp4',kind:'video'},{name:'需求简报.pdf',kind:'pdf'},{name:'说明文档.txt',kind:'text'}]

function fileKind(file){if(file.type?.startsWith('image/'))return'image';if(file.type?.startsWith('video/'))return'video';return file.name.toLowerCase().endsWith('.pdf')?'pdf':'text'}

function FileChip({file,index,onRemove}){const Icon=file.kind==='image'?Image:file.kind==='video'?GalleryHorizontalEnd:file.kind==='pdf'?FileText:Code2;return <span className={`attachment-chip attachment-${file.kind}`} title={file.name}><i className={file.kind==='image'||file.kind==='video'?'attachment-thumb':'attachment-type'}>{file.preview?(file.kind==='image'?<img src={file.preview} alt=""/>:<video src={file.preview} muted/>):<Icon/>}{file.kind==='video'&&<em><Play/></em>}</i><button aria-label={`移除附件 ${index+1}`} onClick={()=>onRemove(index)}><X/></button></span>}

export default function AgentPromptComposer({onSend,running}){const [mode,setMode]=useState('agent');const [value,setValue]=useState('结合已添加的附件，构建一个待办事项应用。');const [model,setModel]=useState(models.agent[0]);const [modelOpen,setModelOpen]=useState(false);const [files,setFiles]=useState(initialFiles);const fileInput=useRef(null);const chooseMode=next=>{setMode(next);setModel(models[next][0]);setModelOpen(false)};const addFiles=list=>{const added=Array.from(list).map(file=>{const kind=fileKind(file);return{name:file.name,kind,preview:kind==='image'||kind==='video'?URL.createObjectURL(file):null}});setFiles(current=>[...current,...added])};const submit=()=>{if(running){onSend('');return}const text=value.trim();if(!text)return;onSend(text)};return <div className={`prompt-state-card state-multi mode-${mode} agent-prompt-composer`}><input ref={fileInput} type="file" hidden multiple accept="image/*,video/*,.pdf,.txt,.doc,.docx" onChange={event=>addFiles(event.target.files)}/><div className="prompt-mode-tabs" role="tablist" aria-label="生成类型">{modes.map(([id,Icon,label])=><button role="tab" aria-selected={mode===id} className={mode===id?'active':''} onClick={()=>chooseMode(id)} key={id}><Icon/>{label}</button>)}</div><div className="file-row compact-attachments">{files.map((file,index)=><FileChip file={file} index={index} onRemove={removeIndex=>setFiles(current=>current.filter((_,itemIndex)=>itemIndex!==removeIndex))} key={`${file.name}-${index}`}/>) }<button className="add-file" aria-label="添加附件" onClick={()=>fileInput.current?.click()}><Plus/></button></div><textarea value={value} onChange={event=>setValue(event.target.value)} onKeyDown={event=>{if((event.ctrlKey||event.metaKey)&&event.key==='Enter')submit()}} placeholder={placeholders[mode]} aria-label="输入任务"/><div className="state-actions"><div><button title="添加附件" aria-label="添加附件" onClick={()=>fileInput.current?.click()}><Paperclip/></button><button title="提及成员" aria-label="提及成员" onClick={()=>setValue(current=>`${current}${current?' ':''}@成员 `)}><AtSign/></button></div><div className="state-model-wrap"><button className="state-model" onClick={()=>setModelOpen(open=>!open)}><Sparkles/>{model}<ChevronDown/></button>{modelOpen&&<div className="state-model-menu">{models[mode].map(item=><button className={item===model?'active':''} onClick={()=>{setModel(item);setModelOpen(false)}} key={item}>{item}{item===model&&<Check/>}</button>)}</div>}</div><button className={`state-send ${running?'is-running':''}`} title={running?'停止':'发送'} onClick={submit}>{running?<Square/>:<ArrowUp/>}</button></div></div>}
