import React, { useEffect, useLayoutEffect, useMemo, useRef, useState } from 'react'
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUp, Box, Check, ChevronDown, ChevronRight, Download, ExternalLink, FileBarChart, Film, FolderOpen, GalleryVerticalEnd, Grid2X2, Image, LayoutGrid, Link2, List, MoreHorizontal, Package, Pencil, Plus, Search, ShieldCheck, SlidersHorizontal, Sparkles, Trash2, Upload, Users, X } from 'lucide-react'
import { gsap } from 'gsap'

const currentUserId = 'user_1024'
const sourceAvatarColor=name=>`avatar-color-${Array.from(name||'').reduce((total,char)=>total+char.codePointAt(0),0)%9}`

const emptyPopulationTest=index=>({group:`营销组别 ${String(index+1).padStart(2,'0')}`,audience:'',painPoint:'',result:'',feature:'',benefit:'',creative:''})

function PopulationTestsEditor({ groups, onChange }) {
  const update=(index,key,value)=>onChange(groups.map((group,groupIndex)=>groupIndex===index?{...group,[key]:value}:group))
  const add=()=>{if(groups.length<10)onChange([...groups,emptyPopulationTest(groups.length)])}
  const remove=index=>onChange(groups.length===1?[emptyPopulationTest(0)]:groups.filter((_,groupIndex)=>groupIndex!==index).map((group,groupIndex)=>({...group,group:`营销组别 ${String(groupIndex+1).padStart(2,'0')}`})))
  const fields=[['audience','目标人群',Users],['painPoint','核心痛点',ShieldCheck],['result','核心结果',Check],['feature','对应原始卖点',Package],['benefit','对应买点内容',SlidersHorizontal],['creative','素材方向',Film]]
  return <section className="population-tests-editor"><div className="population-tests-heading"><Users aria-hidden="true"/><label>分人群营销实验库</label><span>{groups.length}/10</span></div><div className="population-test-list">{groups.map((group,index)=><article key={group.group||index}><header><strong>{`营销组别 ${String(index+1).padStart(2,'0')}`}</strong><button type="button" onClick={()=>remove(index)} aria-label={`删除营销组别 ${String(index+1).padStart(2,'0')}`}><X/></button></header><div>{fields.map(([key,label,Icon])=><label key={key} htmlFor={`population-test-${index}-${key}`}><span><Icon aria-hidden="true"/>{label}</span><textarea rows={1} id={`population-test-${index}-${key}`} value={group[key]||''} onChange={event=>update(index,key,event.target.value)} placeholder={`填写${label}`}/></label>)}</div></article>)}</div>{groups.length<10&&<button type="button" className="population-test-add" onClick={add}><Plus/>添加营销组别</button>}</section>
}

function ProductDetails({ item }) {
  return <div className="product-detail-modules"><section className="detail-section product-information"><header className="product-module-heading"><span><Package aria-hidden="true"/></span><div><h3>商品信息</h3><small>商品定位与核心受众</small></div></header><dl><div><dt>商品描述</dt><dd>{item.description||'暂未填写'}</dd></div><div><dt>核心场景</dt><dd>{item.coreScenario||'暂未填写'}</dd></div><div><dt>目标受众</dt><dd>{item.targetAudience||'暂未填写'}</dd></div></dl></section><section className="detail-section product-buying-points"><header className="product-module-heading"><span><Users aria-hidden="true"/></span><div><h3>分人群营销实验库</h3><small>{item.buyingPointGroups?.length||0} 个营销组别</small></div></header>{item.buyingPointGroups?.length?<div className="buying-point-groups">{item.buyingPointGroups.map((group,index)=><article key={`${group.group}-${index}`}><header><strong>{`营销组别 ${String(index+1).padStart(2,'0')}`}</strong><span>{group.audience}</span></header><dl><div><dt>目标人群</dt><dd>{group.audience}</dd></div><div><dt>核心痛点</dt><dd>{group.painPoint}</dd></div><div><dt>核心结果</dt><dd>{group.result}</dd></div><div><dt>对应原始卖点</dt><dd>{group.feature}</dd></div><div><dt>对应买点内容</dt><dd>{group.benefit}</dd></div><div><dt>素材方向</dt><dd>{group.creative}</dd></div></dl></article>)}</div>:<p className="product-detail-empty">暂未配置</p>}</section></div>
}

function RelatedAttachments({ attachments }) {
  return <div className="related-attachments" aria-label={`${attachments.length} 个相关附件`}>{attachments.map((url,index)=><span className="related-attachment" tabIndex="0" aria-label={`附件 ${index+1}`} key={`${url}-${index}`}><img src={url} alt="" loading="lazy" referrerPolicy="no-referrer"/><span className="related-attachment-popover" role="tooltip"><img src={url} alt={`附件 ${index+1} 预览`} loading="lazy" referrerPolicy="no-referrer"/><b>附件 {String(index+1).padStart(2,'0')}</b></span></span>)}</div>
}

function PromptContent({ prompt, attachments, expanded, onToggle }) {
  return <div className={`collection-prompt ${expanded?'is-expanded':''}`}><div><span>{prompt.slice(0,54)}</span>{attachments.slice(0,2).map((url,index)=><span className="prompt-attachment-reference" title={`引用附件 ${index+1}`} key={`${url}-${index}`}><b>@</b><img src={url} alt="" loading="lazy" referrerPolicy="no-referrer"/>附件{String(index+1).padStart(2,'0')}</span>)}<span>{prompt.slice(54)}</span></div>{prompt.length>240&&<button type="button" onClick={onToggle} aria-expanded={expanded}>{expanded?'收起':'展开'}<ChevronDown aria-hidden="true"/></button>}</div>
}

// 仅引用花瓣公开页面实际加载的高清 CDN 资源，不把图片写入项目。
const huabanMedia = {
  square: 'https://gaoding-market.dancf.com/market-operations/market/side/503baea7b7334985a68b4f965d56d0c7/1782096304506.png',
  portraitXL: 'https://gaoding-market.dancf.com/market-operations/market/side/334fee6d3f1f41fdb2564b4a4c05f2c4/1784873106117.jpg',
  posterA: 'https://gaoding-market.dancf.com/market-operations/market/side/1abf5ea59f3c46a08cf3a15955a76bb9/1784873226168.jpg',
  posterB: 'https://gaoding-market.dancf.com/market-operations/market/side/f3353952a7654dfa86ebecd1d285480d/1784873241959.png',
  posterC: 'https://gaoding-market.dancf.com/market-operations/market/side/8a9a68d6e4cc48348850217ae88c187c/1784873235764.png',
  lightA: 'https://gaoding-market.dancf.com/market-operations/market/side/9ede3f56c49940e3900741daa42bc802/1784873116557.jpg',
  demoVideo: 'https://lf9-cdn-tos.bytecdntp.com/cdn/expire-1-M/byted-player-videos/1.0.0/xgplayer-demo.mp4',
}

const providedImages = [
  "https://p26-dreamina-sign.byteimg.com/tos-cn-i-tb4s082cfz/226faf82fe5c4e2aab443bc5b904906b~tplv-tb4s082cfz-aigc_resize:2048:2048.webp?lk3s=4fa96020&x-expires=1789776000&x-signature=3B1M3OPDxVRVnH7aCIZFp3WF9xQ%3D",
  "https://p26-dreamina-sign.byteimg.com/tos-cn-i-tb4s082cfz/c1e72a1c5b7344b8b7c93537d0f0f8f4~tplv-tb4s082cfz-aigc_resize:2048:2048.webp?lk3s=4fa96020&x-expires=1789776000&x-signature=AyF3cMvm0GmLDl2qI%2FcPsbqbDRk%3D",
  "https://p26-dreamina-sign.byteimg.com/tos-cn-i-tb4s082cfz/7dc5a08a6dce4644bc31a7f2bc698e79~tplv-tb4s082cfz-aigc_resize:2048:2048.webp?lk3s=4fa96020&x-expires=1789776000&x-signature=y8N1ZGwvxRyRi5EnCRoHI53%2BxBk%3D",
  "https://p26-dreamina-sign.byteimg.com/tos-cn-i-tb4s082cfz/7cb06f6910d04108a85906b5a1aa91fc~tplv-tb4s082cfz-aigc_resize:2048:2048.webp?lk3s=4fa96020&x-expires=1789776000&x-signature=HeYza0lDY8uvhaK44D6rB7xUG7I%3D",
  "https://p11-dreamina-sign.byteimg.com/tos-cn-i-tb4s082cfz/2fc8918f7f6e4368afacc465c31303d2~tplv-tb4s082cfz-aigc_resize:2048:2048.webp?lk3s=4fa96020&x-expires=1789776000&x-signature=Dbjz0XzL4CKmrrvpG8y3pMVntfs%3D",
  "https://p26-dreamina-sign.byteimg.com/tos-cn-i-tb4s082cfz/8c823a4d335649a2851dc21471091a99~tplv-tb4s082cfz-aigc_resize:2048:2048.webp?lk3s=4fa96020&x-expires=1789776000&x-signature=CwEJbem9Sc1zWUbCGAT7UIDBcB0%3D",
  "https://p26-dreamina-sign.byteimg.com/tos-cn-i-tb4s082cfz/3beeaee337dc40beba2dbc6ff039a699~tplv-tb4s082cfz-aigc_resize:2048:2048.webp?lk3s=4fa96020&x-expires=1789776000&x-signature=uFcNWoBxBpLzXCShcHGdmiMzi2o%3D",
  "https://p26-dreamina-sign.byteimg.com/tos-cn-i-tb4s082cfz/a5b6313eedd946b295344011f4e3137b~tplv-tb4s082cfz-aigc_resize:2048:2048.webp?lk3s=4fa96020&x-expires=1789776000&x-signature=TgTN0shqv47ZS7whs6sZWqUg8oQ%3D",
  "https://p26-dreamina-sign.byteimg.com/tos-cn-i-tb4s082cfz/9934059498bd4b54977cf5e73b135ec9~tplv-tb4s082cfz-aigc_resize:2048:2048.webp?lk3s=4fa96020&x-expires=1789776000&x-signature=zKk6R8gxUhZ%2BtHW3Z51YKXvisKQ%3D",
  "https://p26-dreamina-sign.byteimg.com/tos-cn-i-tb4s082cfz/f35d9d2b808347bfa821cba13842987c~tplv-tb4s082cfz-aigc_resize:2048:2048.webp?lk3s=4fa96020&x-expires=1789776000&x-signature=ybhQjCtUxrYvRxE9D4GhAT24LAE%3D",
  "https://p26-dreamina-sign.byteimg.com/tos-cn-i-tb4s082cfz/9d019298d6af4379a9ab89d523ec4b49~tplv-tb4s082cfz-aigc_resize:2048:2048.webp?lk3s=4fa96020&x-expires=1789776000&x-signature=%2FPPgEzaqdU5CpTEb3Q8aIc1jz48%3D",
  "https://p26-dreamina-sign.byteimg.com/tos-cn-i-tb4s082cfz/c5f061614f87462491396e28a5cd320b~tplv-tb4s082cfz-aigc_resize:2048:2048.webp?lk3s=4fa96020&x-expires=1789776000&x-signature=AeTMunBxxXYSH9Jf%2BxMaWMzndoM%3D",
  "https://p11-dreamina-sign.byteimg.com/tos-cn-i-tb4s082cfz/2286b76f84d0441e83e24045839264c6~tplv-tb4s082cfz-aigc_resize:2048:2048.webp?lk3s=4fa96020&x-expires=1789776000&x-signature=alw%2FhzUGKpSCJRulxNT4GvWMoOc%3D",
  "https://p11-dreamina-sign.byteimg.com/tos-cn-i-tb4s082cfz/41c2a85788d44f9d9fed145f2e9b3097~tplv-tb4s082cfz-aigc_resize:2048:2048.webp?lk3s=4fa96020&x-expires=1789776000&x-signature=tHlGiSUvR1CizbbMXEWPQ8ICixk%3D"
]
export { providedImages as mockPreviewImages }
const providedVideos = [
  "https://v6-artist.vlabvod.com/61d36cde2787fd42cd52b82e729c1103/6a9fbf59/video/tos/cn/tos-cn-v-148450/oQQQxAqs6Q9c0iDh7EA7gyJcENItecDG4pTZPr/?a=4066&ch=0&cr=0&dr=0&er=0&cd=0%7C0%7C0%7C0&br=6632&bt=6632&cs=0&ds=12&ft=5QYTUxhhe6BMyqTp_2eJD12Nzj&mime_type=video_mp4&qs=0&rc=ZzhnaWU6ZDY0Njo6aWk5ZEBpamttbTxrb2ttOjczNDM7M0A1MDAyLTItNmAxX2AxXjE1YSMuMl9xcWdeb2lhLS1kNC9zcw%3D%3D&btag=80000e00008000&dy_q=1788249300&feature_id=04b16e464b574158bb99cac30ccb1f5e&l=20260901155459E3FB3EFB5393E2E14EFE",
  "https://v26-artist.vlabvod.com/183e2417a43115f3afc8fa76f92d2554/6a9fdfa0/video/tos/cn/tos-cn-v-148450/okoy6bQkBQC7LhAeHTaQEUEyeILe0bDzmtBOBs/?a=4066&ch=0&cr=0&dr=0&er=0&cd=0%7C0%7C0%7C0&br=18242&bt=18242&cs=0&ds=12&ft=5QYTUxhhe6BMyqQhJ2eJD12Nzj&mime_type=video_mp4&qs=0&rc=ZTxnMzw8OmZnZzRmOWU7NkBpampkZTZvOjs5PDczNDM7M0BiLjQxYl9fNi4xYF4yMjQ1YSMtLzNzYWFecnFhLS1kNC9zcw%3D%3D&btag=80000e00008000&dy_q=1788257563&feature_id=04b16e464b574158bb99cac30ccb1f5e&l=202609011812425E09B75C6C7B56CE7ABB",
  "https://v9-artist.vlabvod.com/8825e13449be5c7e9bce3c3c542dd1bf/6a9fdfb0/video/tos/cn/tos-cn-v-148450/o0UFNWEEhgEkdJ4MIqwQ9aIxjrQmIXbQbt0TK/?a=4066&ch=0&cr=0&dr=0&er=0&cd=0%7C0%7C0%7C0&br=2137&bt=2137&cs=0&ds=4&ft=5QYTUxhhe6BMyqDhJ2eJD12Nzj&mime_type=video_mp4&qs=0&rc=ZTwzNTdkNzVoMzQ6OzZnZkBpM2RrO2VvOnJmPDczNDM7M0AzMy1iXmNgNTAxL18xXi5eYSMxa3IzYWFeNmZhLS1kNC9zcw%3D%3D&btag=80000e00010000&dy_q=1788257564&feature_id=f0150a16a324336cda5d6dd0b69ed299&l=202609011812446B0F4F052E8766D7BB40",
  "https://v9-artist.vlabvod.com/5960d4f4b8cb2181da36c666a489d619/6a9fdfa6/video/tos/cn/tos-cn-v-148450/owoJHJZ1a1YSIQ7oWqftgDTaAsXMOEgzzAhJQA/?a=4066&ch=0&cr=0&dr=0&er=0&cd=0%7C0%7C0%7C0&br=18838&bt=18838&cs=0&ds=12&ft=5QYTUxhhe6BMyqDhJ2eJD12Nzj&mime_type=video_mp4&qs=0&rc=MzxpZzs7PGlpMzs8ZDYzZ0BpMzxvNjNvOjdvPDczNDM7M0BgYl40MC9fNjExMV4vNTUtYSMzci81YWFuZ21hLS1kNC9zcw%3D%3D&btag=80000e00008000&dy_q=1788257564&feature_id=04b16e464b574158bb99cac30ccb1f5e&l=202609011812446B0F4F052E8766D7BB40",
  "https://v9-artist.vlabvod.com/9702fd5252fa4730af04d9f24dc77faa/6a9fdfa1/video/tos/cn/tos-cn-v-148450/oYNoEtaFJTOg9aJfEdjAcankaq7DR1MhQQAIIx/?a=4066&ch=0&cr=0&dr=0&er=0&cd=0%7C0%7C0%7C0&br=22035&bt=22035&cs=0&ds=12&ft=5QYTUxhhe6BMyqDhJ2eJD12Nzj&mime_type=video_mp4&qs=0&rc=Zmk0Njs0ZmlnOmY6N2U4NUBpank7cDdvOmg7ZDczNDM7M0BhLy5jYV9gXzExYjYwL2ItYSNiYjNqYWFebjFhLS1kNC9zcw%3D%3D&btag=80000e00008000&dy_q=1788257564&feature_id=04b16e464b574158bb99cac30ccb1f5e&l=202609011812446B0F4F052E8766D7BB40",
  "https://v9-artist.vlabvod.com/41b9dbae77542a8c70fd0ab43bdde94b/6a9fdfa1/video/tos/cn/tos-cn-v-148450/oksXtgCDpBK7woVFEIixfSQNHA2mfsVgmBI6FO/?a=4066&ch=0&cr=0&dr=0&er=0&cd=0%7C0%7C0%7C0&br=6904&bt=6904&cs=0&ds=12&ft=5QYTUxhhe6BMyqDhJ2eJD12Nzj&mime_type=video_mp4&qs=0&rc=OTpoO2g0M2dpNDs8PGRmNkBpM3JmZnc5cm1rOTczNDM7M0AtMGBjLl42NTMxLzFhYF82YSNfaW9nMmRrX21hLS1kNC9zcw%3D%3D&btag=80000e00008000&dy_q=1788257564&feature_id=04b16e464b574158bb99cac30ccb1f5e&l=202609011812446B0F4F052E8766D7BB40"
]
const localDemoVideos = [1,2,3,4,5,7,8,9,10,11,12].map(index=>`${import.meta.env.BASE_URL}demo-videos/demo-video-${String(index).padStart(2,'0')}.mp4`)
const localVideoSpecs = [
  {ratio:'31:54',clarity:'864P',duration:'00:15',fileSize:'2.8 MB'},
  {ratio:'31:54',clarity:'864P',duration:'00:15',fileSize:'3.4 MB'},
  {ratio:'31:54',clarity:'864P',duration:'00:15',fileSize:'2.8 MB'},
  {ratio:'9:16',clarity:'720P',duration:'00:15',fileSize:'8.7 MB'},
  {ratio:'31:54',clarity:'864P',duration:'00:15',fileSize:'4.5 MB'},
  {ratio:'16:9',clarity:'720P',duration:'00:05',fileSize:'4.3 MB'},
  {ratio:'9:16',clarity:'720P',duration:'00:10',fileSize:'23.1 MB'},
  {ratio:'7:3',clarity:'630P',duration:'00:05',fileSize:'13.6 MB'},
  {ratio:'540:953',clarity:'1080P',duration:'00:21',fileSize:'5.4 MB'},
  {ratio:'9:16',clarity:'1080P',duration:'00:07',fileSize:'2.0 MB'},
  {ratio:'9:16',clarity:'1080P',duration:'01:51',fileSize:'12.6 MB'},
]

const healthBuyingPointGroups = [
  {group:'营销组别 01',related:'买点 01 + 买点 05',audience:'PCOS 确诊及疑似多囊女性',painPoint:'长期胰岛素抵抗与雄激素过高，会造成月经稀发甚至闭经，进而出现严重的痤疮与脱发，同时伴随排卵障碍，一步步引发“多囊综合征候群”。',result:'恢复规律月经周期与排卵功能',feature:'MYO-INOSITOL FULL SPECTRUM FORMULA, D-CHIRO INOSITOL, BERBERINE, VITAMIN D3 + K2',benefit:'买点 01：利用 40:1 黄金比例肌醇与小檗碱协同作用，从源头改善胰岛素敏感性，重启卵巢正常排卵机制',creative:'医生科普风 / PCOS 复查对比图 / 激素六项单解读'},
  {group:'营销组别 02',related:'买点 02 + 买点 06',audience:'高压职场女性 / 过劳肥人群',painPoint:'长期精神紧绷与皮质醇水平异常，会造成腹部脂肪顽固堆积，叠加深夜情绪性暴食，最终引发“压力型向心性肥胖”。',result:'flatten 小肚腩与阻断情绪性进食',feature:'CORTISOL-HEALTH FULL SPECTRUM FORMULA, ASHWAGANDHA, MAGNESIUM, L-THEANINE',benefit:'买点 02：通过南非醉茄与镁元素双重调节，将体内压力激素皮质醇降至正常水平，物理切断压力肥成因',creative:'职场 Vlog / 皮质醇自测表 / 腰围变化实录'},
  {group:'营销组别 03',related:'买点 03 + 买点 07',audience:'严重失眠与焦虑人群',painPoint:'长期思虑过度与神经兴奋，会造成入睡困难与早醒，进而出现日间脑雾与注意力涣散，同时伴随情绪易怒，一步步引发“慢性疲劳综合征”。',result:'深度安神助眠与情绪稳态重塑',feature:'PASSIONFLOWER, MAGNOLIA BARK, VALERIAN ROOT, LEMON BALM, HOLY BASIL, PHOSPHATIDYLSERINE, RHODIOLA ROSEA, LAVENDER OIL, CHAMOMILE, GABA',benefit:'买点 03：集结西番莲、木兰皮等 9 种天然草本镇静剂，全方位安抚过载神经，实现无依赖的自然深睡',creative:'沉浸式 ASMR / 睡前仪式感 / 睡眠监测 APP 数据截图'},
  {group:'营销组别 04',related:'买点 04 + 买点 08',audience:'代谢停滞与减重平台期人群',painPoint:'长期细胞能量代谢受阻，会造成体脂率居高不下，叠加线粒体功能衰退，最终引发“顽固性代谢迟缓”。',result:'激活细胞燃脂引擎与提升基础代谢',feature:'CEYLON CINNAMON, ALPHA LIPOIC ACID, BLACK PEPPER, BITTER MELON, CHROMIUM, VITAMIN B12, FOLATE, CoQ10, ZINC, DIM',benefit:'买点 04：锡兰肉桂配合 α-硫辛酸与辅酶 Q10，直接优化细胞线粒体供能效率，让身体重新变成高效燃脂机器',creative:'健身餐搭配 / 代谢率测试 / 平台期突破打卡'},
  {group:'营销组别 05',related:'买点 05 + 买点 09',audience:'备孕困难与激素失调女性',painPoint:'长期内分泌环境紊乱，会造成卵子质量下降，进而出现黄体功能不全，同时伴随子宫内膜容受性差，一步步引发“难孕体质”。',result:'营造优质受孕环境与养卵护巢',feature:'MYO-INOSITOL, D-CHIRO INOSITOL, VITAMIN D3 + K2, FOLATE, DIM',benefit:'买点 05：肌醇与活性叶酸、DIM 吲哚甲醇强强联合，精准调节雌孕激素平衡，为受精卵着床打造黄金土壤',creative:'好孕分享 / 备孕清单 / 营养素成分深扒'},
  {group:'营销组别 06',related:'买点 06 + 买点 10',audience:'经前综合征（PMS）严重者',painPoint:'长期激素波动剧烈，会造成经前乳房胀痛与水肿，叠加情绪抑郁暴躁，最终引发“周期性身心折磨”。',result:'平稳度过经期与消除经前不适',feature:'CORTISOL-HEALTH, MAGNESIUM, GABA, MYO-INOSITOL, VITAMIN B6 (implied in B-complex), ZINC',benefit:'买点 06：镁元素与 GABA 协同舒缓平滑肌痉挛，配合肌醇稳定血清素，从生理到心理全面抚平经期风暴',creative:'经期日历记录 / PMS 症状缓解前后对比 / 闺蜜谈心视角'},
  {group:'营销组别 07',related:'买点 07 + 买点 11',audience:'糖瘾严重与血糖波动人群',painPoint:'长期高糖饮食与血糖过山车，会造成餐后极度困倦与 cravings，进而出现皮肤糖化暗沉，同时伴随脂肪合成加速，一步步引发“糖化衰老与肥胖”。',result:'平稳血糖曲线与抗糖抗氧',feature:'BERBERINE, BITTER MELON, CHROMIUM, CEYLON CINNAMON, ALPHA LIPOIC ACID',benefit:'买点 07：小檗碱与苦瓜提取物充当天然“碳水阻断剂”，铬元素提升胰岛素效能，从源头掐断糖分转化为脂肪的路径',creative:'控糖饮食挑战 / 连续血糖仪（CGM）实测数据 / 抗糖护肤内调逻辑'},
  {group:'营销组别 08',related:'买点 08 + 买点 12',audience:'产后修复与更年期女性',painPoint:'长期雌激素撤退与身心双重压力，会造成潮热盗汗与情绪崩溃，叠加骨密度流失风险，最终引发“早衰综合征”。',result:'滋养卵巢延缓衰老与强骨护心',feature:'MYO-INOSITOL, VITAMIN D3 + K2, CoQ10, ZINC, DIM, CORTISOL-HEALTH, ASHWAGANDHA',benefit:'买点 08：维生素 D3 + K2 锁钙入骨，辅酶 Q10 养护心脏，配合南非醉茄适应原特性，帮助身体平稳度过激素断崖期',creative:'年龄感反差 / 更年期症状自查 / 女性全生命周期养护理念'},
]

const productProfiles = {
  '旅行保温杯':{coreScenario:'通勤、差旅与户外活动中的随身饮水和长效保温。',targetAudience:'注重便携性、饮水品质与简洁设计的通勤人士和户外用户。',sellingPoints:['轻量杯身，单手即可开合','长效保温保冷，满足全天饮水需求','食品级内胆，不易残留气味']},
  '无线桌面音箱':{coreScenario:'高压崩溃场景：职场高压、长期熬夜、焦虑失眠导致的“过劳肥”与情绪失控。\n生理紊乱场景：月经不调、PCOS、备孕困难、顽固性痤疮与脱发。\n代谢停滞场景：节食无效、体重平台期、嗜糖成瘾、饭后极度困倦。',targetAudience:'核心人群：25-40 岁都市女性，特别是被诊断为 PCOS 或处于亚健康高压状态的职业女性与宝妈。\n心理特征：对传统单一减肥法绝望，深受情绪性进食困扰，渴望通过科学成分从根本上解决身体失控感，追求“身心同调”的安全感。',sellingPoints:healthBuyingPointGroups.map(group=>group.benefit),buyingPointGroups:healthBuyingPointGroups},
  '植物精华礼盒':{coreScenario:'日常护肤、节日赠礼与旅行期间的成套肌肤护理。',targetAudience:'关注温和配方、植物成分与精致送礼体验的护肤用户。',sellingPoints:['精选植物精华，温和滋养肌肤','完整护理组合，一盒覆盖日常流程','礼盒包装精致，送礼自用皆宜']},
  '轻量通勤背包':{coreScenario:'日常通勤、短途出行与移动办公时的设备和随身物品收纳。',targetAudience:'需要轻量负重、分区收纳和简洁外观的城市通勤人群。',sellingPoints:['轻量耐磨面料，久背不易疲劳','电脑独立防护仓，通勤收纳更安心','多分区设计，小物取用更高效']},
  '香氛蜡烛套装':{coreScenario:'居家放松、睡前仪式与节日氛围营造。',targetAudience:'重视生活氛围、香气层次和家居美感的品质生活人群。',sellingPoints:['多种香调组合，适配不同心情与空间','植物蜡基底，燃烧稳定更安心','简约杯器可融入多种家居风格']},
  '家用咖啡机':{coreScenario:'家庭早餐、居家办公和朋友聚会时快速制作咖啡。',targetAudience:'希望在家稳定获得咖啡馆口感，同时重视操作效率的咖啡爱好者。',sellingPoints:['一键萃取，新手也能快速上手','稳定温控，充分释放咖啡风味','可拆洗结构，日常清洁更省心']},
  '户外露营灯':{coreScenario:'露营照明、夜间徒步与停电应急。',targetAudience:'关注续航、防护性能和多场景照明的露营及户外活动用户。',sellingPoints:['多档亮度可调，兼顾照明与氛围','长续航电池，满足整夜使用','轻量防泼水设计，户外携带更可靠']},
  '丝绒口红礼盒':{coreScenario:'日常妆容、重要约会和节日赠礼。',targetAudience:'偏爱高级哑光妆效、丰富色彩和精致包装的彩妆用户。',sellingPoints:['丝绒哑光质地，显色同时保持顺滑','精选实用色组，覆盖多种妆容场合','礼盒设计精致，提升送礼仪式感']},
}
const productProfile=name=>productProfiles[name]||{coreScenario:'商品展示、日常使用与内容创作场景。',targetAudience:'关注产品品质、实用体验与视觉表达的目标消费者。',sellingPoints:['核心功能清晰，满足日常使用需求','设计简洁耐看，适配多种使用环境','细节品质可靠，兼顾实用与体验']}

const seedAssets = [
  { id:'asset_0188', name:'品牌光效视觉', description:'用于品牌活动主视觉的方形光影素材。', type:'图片', group:'素材库', scope:'个人资产', source:'林屿', url:huabanMedia.square, previewUrl:huabanMedia.square, resolution:'2000 × 2000', ratio:'1:1', fileType:'PNG', fileSize:'4.6 MB', tone:'ocean', date:'今天 14:32', creatorId:currentUserId },
  { id:'asset_0187', name:'竖屏动态作品 01', description:'AI 生成的竖屏动态视觉素材。', type:'视频', group:'素材库', scope:'个人资产', source:'林屿', url:localDemoVideos[0], previewUrl:providedImages[0], ...localVideoSpecs[0], fileType:'MP4', tone:'lime', date:'今天 11:08', creatorId:currentUserId },
  { id:'work_0096', name:'东方美学人物海报', description:'东方人物造型与留白排版结合的竖版视觉提案。', type:'图片作品', group:'作品收藏', scope:'个人资产', source:'林屿', url:huabanMedia.posterA, previewUrl:huabanMedia.posterA, relatedAttachments:[huabanMedia.posterA,huabanMedia.posterB,huabanMedia.posterC], taskId:'task_0096', prompt:'设计一张竖版东方美学人物主题海报，整体气质克制、宁静且具有现代杂志感。画面以人物为视觉中心，突出侧脸轮廓、服装垂坠质感与细腻面料细节，人物姿态自然、情绪内敛，避免夸张表情与僵硬摆拍。结合附件中的色彩、纹理和版式参考，以暖白、沙色、淡墨黑为主色，局部加入低饱和朱红作为视觉锦点。采用柔和的自然侧光，保留真实的皮肤质感和轻微阴影，避免过度磨皮、高饱和配色与强烈电影光效。构图采用非对称留白，为主标题、副标题与日期信息预留明确安全区，中英文字体层级简洁，注意字号、字距和行距的呼吸感。背景可融入抽象山水、宣纸纤维或东方建筑影子，但不要堆叠具象符号。最终画面需兼顾文化感与当代商业视觉，细节清晰，高级、耐看，适合线上发布与纸张印刷。输出时请确保主体边缘完整，衣料纹理与发丝细节自然，避免手指畸变、五官失真、文字乱码和过度锐化。预留上下裁切空间，使画面在手机竖屏、社交媒体封面与展览印刷三种场景中都能保持视觉重心和清晰层级。', skill:'海报视觉生成', model:'Seedream 4.0', ratio:'720:1019', resolution:'1440 × 2038', fileType:'JPG', fileSize:'3.9 MB', tone:'rose', date:'昨天 18:40', creatorId:currentUserId },
  { id:'work_0095', name:'竖屏动态作品 02', description:'根据生成记录收藏的竖屏视频作品。', type:'视频作品', group:'作品收藏', scope:'个人资产', source:'林屿', url:localDemoVideos[1], previewUrl:providedImages[1], taskId:'task_0095', prompt:'竖屏构图，主体清晰，镜头自然运动，画面细节稳定。', skill:'文生视频', model:'Seedance 2.0', ...localVideoSpecs[1], fileType:'MP4', tone:'night', date:'昨天 16:22', creatorId:currentUserId },
  { id:'product_0042', name:'便携榨汁杯组合', description:'商品主图、细节图与使用场景图合集。', ...productProfile('便携榨汁杯组合'), type:'商品图片', group:'商品资产', scope:'个人资产', source:'林屿', url:'https://assets.shulan.ai/products/product_0042', images:[huabanMedia.square,huabanMedia.posterA,huabanMedia.posterB,huabanMedia.lightA,huabanMedia.portraitXL,huabanMedia.posterC], previewUrl:huabanMedia.square, imageCount:6, resolution:'2000 × 2000', fileType:'图片集', fileSize:'28.3 MB', tone:'peach', date:'8 月 29 日', creatorId:currentUserId },
  { id:'product_0014', name:'夏季饮品礼盒', description:'包含礼盒主图、包装细节和饮用场景图。', ...productProfile('夏季饮品礼盒'), type:'商品图片', group:'商品资产', scope:'个人资产', source:'林屿', url:'https://assets.shulan.ai/products/product_0014', images:providedImages.slice(2,8), previewUrl:providedImages[2], imageCount:6, resolution:'1152 × 2048', fileType:'图片集', fileSize:'22.6 MB', tone:'peach', date:'8 月 28 日', creatorId:currentUserId },
  { id:'team_0031', name:'品牌视觉规范 2026', description:'团队统一使用的品牌色、字体和版式规范。', type:'图片', group:'素材库', scope:'团队资产', source:'林屿', url:huabanMedia.portraitXL, previewUrl:huabanMedia.portraitXL, resolution:'2211 × 2361', ratio:'737:787', fileType:'JPG', fileSize:'5.8 MB', tone:'cobalt', date:'8 月 25 日', creatorId:currentUserId },
  { id:'team_0029', name:'团队竖屏视频 01', description:'团队共享的 AI 竖屏视频素材。', type:'视频', group:'素材库', scope:'团队资产', source:'周一鸣', url:localDemoVideos[2], previewUrl:providedImages[2], ...localVideoSpecs[2], fileType:'MP4', tone:'amber', date:'8 月 23 日', creatorId:'user_2048' },
  { id:'team_product_08', name:'团队标准商品图', description:'团队共用的商品白底图、细节图和场景图。', ...productProfile('团队标准商品图'), type:'商品图片', group:'商品资产', scope:'团队资产', source:'林屿', url:'https://assets.shulan.ai/products/team_product_08', images:[huabanMedia.posterC,huabanMedia.square,huabanMedia.posterA,huabanMedia.lightA,huabanMedia.posterB,huabanMedia.portraitXL,huabanMedia.square,huabanMedia.posterC], previewUrl:huabanMedia.posterC, imageCount:8, resolution:'1200 × 1600', fileType:'图片集', fileSize:'36.1 MB', tone:'peach', date:'8 月 22 日', creatorId:currentUserId },
  { id:'team_product_03', name:'秋季新品组合', description:'团队共享的新品主图、细节图和场景图合集。', ...productProfile('秋季新品组合'), type:'商品图片', group:'商品资产', scope:'团队资产', source:'周一鸣', url:'https://assets.shulan.ai/products/team_product_03', images:providedImages.slice(6,12), previewUrl:providedImages[6], imageCount:6, resolution:'1152 × 2048', fileType:'图片集', fileSize:'26.8 MB', tone:'peach', date:'8 月 20 日', creatorId:'user_2048' },
]

const demoImages = providedImages
const imageSpecs = [['2000 × 2000','1:1'],['2211 × 2361','737:787'],['1440 × 2038','720:1019'],['1200 × 1604','300:401'],['1200 × 1600','3:4'],['1500 × 1896','125:158']]
const imageNames = ['竖屏视觉作品 01','竖屏视觉作品 02','竖屏视觉作品 03','竖屏视觉作品 04','竖屏视觉作品 05','竖屏视觉作品 06','竖屏视觉作品 07','竖屏视觉作品 08']
const videoNames = ['竖屏动态作品 01','竖屏动态作品 02','竖屏动态作品 03','竖屏动态作品 04','竖屏动态作品 05','竖屏动态作品 06']
const productNames = ['旅行保温杯','无线桌面音箱','植物精华礼盒','轻量通勤背包','香氛蜡烛套装','家用咖啡机','户外露营灯','丝绒口红礼盒']
const reportNames = ['春季内容趋势报告','新品投放复盘','用户画像分析','短视频渠道周报','品牌搜索洞察']

const generatedAssets = Array.from({length:60},(_,index)=>{
  const sequence=index+1
  const scope=index>=40?'个人资产':index%4===0?'团队资产':'个人资产'
  const creatorId=scope==='团队资产'&&index%3===0?'user_2048':currentUserId
  const source=creatorId===currentUserId?'林屿':'周一鸣'
  const imageIndex=index%demoImages.length
  const [resolution,ratio]=['1152 × 2048','9:16']
  const common={scope,source,date:`8 月 ${19-(index%18)} 日`,creatorId}
  if(index%10===7){const images=Array.from({length:5},(_,offset)=>demoImages[(imageIndex+offset)%demoImages.length]);const name=productNames[index%productNames.length];return {id:`product_${String(sequence+120).padStart(4,'0')}`,name,description:'包含商品主图、细节图、包装图和使用场景图。',...productProfile(name),type:'商品图片',group:'商品资产',url:`https://assets.shulan.ai/products/product_${sequence+120}`,images,previewUrl:images[0],imageCount:images.length,resolution,fileType:'图片集',fileSize:`${18+(index%12)}.6 MB`,tone:'peach',...common}}
  if(index%5===3){
    const imageCount=4+(index%5)
    const images=Array.from({length:imageCount},(_,offset)=>demoImages[(imageIndex+offset)%demoImages.length])
    const name=productNames[index%productNames.length]
    return {id:`product_${String(sequence+60).padStart(4,'0')}`,name,description:'包含商品主图、买点细节图、包装图和使用场景图。',...productProfile(name),type:'商品图片',group:'商品资产',url:`https://assets.shulan.ai/products/product_${sequence+60}`,images,previewUrl:images[0],imageCount,resolution,fileType:'图片集',fileSize:`${18+(index%16)}.4 MB`,tone:'peach',...common}
  }
  if(index%3===1){const collected=scope==='个人资产'&&index%2===1;const videoIndex=index%localDemoVideos.length;return {id:`video_${String(sequence+100).padStart(4,'0')}`,name:videoNames[index%videoNames.length],description:'AI 生成的动态视觉素材。',type:collected?'视频作品':'视频',group:collected?'作品收藏':'素材库',url:localDemoVideos[videoIndex],previewUrl:demoImages[imageIndex],taskId:`task_${String(sequence+100).padStart(4,'0')}`,prompt:'主体清晰，镜头自然运动，保留真实材质和空间层次。',skill:'文生视频',model:'Seedance 2.0',...localVideoSpecs[videoIndex],fileType:'MP4',tone:'night',...common}}
  const collected=scope==='个人资产'&&index%4===2
  return {id:`image_${String(sequence+200).padStart(4,'0')}`,name:imageNames[index%imageNames.length],description:'经过筛选整理的高清创意视觉素材。',type:collected?'图片作品':'图片',group:collected?'作品收藏':'素材库',url:demoImages[imageIndex],previewUrl:demoImages[imageIndex],taskId:`task_${String(sequence+200).padStart(4,'0')}`,prompt:'干净构图，真实材质，细腻光影，高分辨率商业视觉。',skill:'视觉生成',model:'Seedream 4.0',ratio,resolution,fileType:imageIndex===0||imageIndex===3||imageIndex===4?'PNG':'JPG',fileSize:`${2+(index%7)}.3 MB`,tone:'ocean',...common}
})

const assets = [...seedAssets,...generatedAssets]

const isVideo = item => item.type.includes('视频')
const summary = item => isVideo(item) ? `${item.ratio} · ${item.clarity} · ${item.duration}` : item.type === '营销报告' ? `PDF · ${item.pages} 页` : item.type === '商品图片' ? `${item.imageCount} 张 · ${item.resolution}` : [item.ratio,item.resolution].filter(Boolean).join(' · ')
const mediaRatio = item => {const raw=item.ratio||item.resolution; if(raw){const [width,height]=raw.split(/[:×]/).map(Number);return width/height}return item.type==='营销报告'?3/4:1}

function Thumb({ item, natural=false, playable=false }) {
  const [intrinsicRatio,setIntrinsicRatio]=useState(null)
  const [mediaFailed,setMediaFailed]=useState(false)
  const ratio=natural&&intrinsicRatio?intrinsicRatio:mediaRatio(item)
  const useEmbeddedPlayer=playable&&isVideo(item)&&item.url?.includes('vlabvod.com')
  useEffect(()=>{setIntrinsicRatio(null);setMediaFailed(false)},[item.previewUrl,item.url])
  const hideFailedMedia=()=>setMediaFailed(true)
  const readImageRatio=event=>{if(natural&&event.currentTarget.naturalHeight)setIntrinsicRatio(event.currentTarget.naturalWidth/event.currentTarget.naturalHeight)}
  return <div className={`managed-asset-thumb ${item.tone} ${natural?'natural-ratio':''} ${mediaFailed?'media-failed':''}`} style={natural?{'--media-ratio':ratio,aspectRatio:ratio}:undefined}><div className="managed-thumb-art"/>{item.previewUrl&&!mediaFailed&&<img key={item.previewUrl} src={item.previewUrl} alt="" loading={natural?'eager':'lazy'} referrerPolicy="no-referrer" onLoad={readImageRatio} onError={hideFailedMedia}/>} {useEmbeddedPlayer?<a className="video-external-preview" href={item.url} target="_blank" rel="noreferrer"><ExternalLink/>新窗口播放</a>:playable&&isVideo(item)&&!mediaFailed&&<video key={item.url} src={item.url} poster={item.previewUrl} controls playsInline preload="metadata" referrerPolicy="no-referrer" onError={hideFailedMedia}/>} {isVideo(item)&&!playable&&<i>▶</i>}</div>
}

function Sidebar({ items, scope, setScope, group, setGroup }) {
  const groups = scope === '个人资产' ? [['素材库',FolderOpen],['作品收藏',GalleryVerticalEnd],['商品资产',Package]] : [['素材库',FolderOpen],['商品资产',Package]]
  const count = name => items.filter(item => item.scope===scope && (name==='全部资产'||item.group===name)).length
  return <aside className="asset-sidebar" aria-label="资产分类"><div className="asset-sidebar-title"><Box/><strong>资产管理</strong></div><div className="scope-switch">{['个人资产','团队资产'].map(name=><button key={name} className={scope===name?'active':''} onClick={()=>{setScope(name);setGroup('全部资产')}}>{name==='个人资产'?<Box/>:<Users/>}{name}</button>)}</div><nav className="asset-tree"><button className={group==='全部资产'?'active':''} onClick={()=>setGroup('全部资产')}><LayoutGrid/><span>全部资产</span><b>{count('全部资产')}</b></button>{groups.map(([name,Icon])=><button key={name} className={group===name?'active':''} onClick={()=>setGroup(name)}><Icon/><span>{name}</span><b>{count(name)}</b></button>)}</nav><div className="asset-storage"><div><span>存储空间</span><b>2.8 GB / 20 GB</b></div><div className="asset-storage-track" role="progressbar" aria-label="存储空间使用量" aria-valuemin="0" aria-valuemax="20" aria-valuenow="2.8"><i/></div></div><div className="asset-sidebar-note"><ShieldCheck/><div><strong>{scope==='个人资产'?'仅你可管理':'团队权限'}</strong><p>{scope==='个人资产'?'复制后会在团队资产中创建副本。':'成员可查看与创建，创建者可修改与删除。'}</p></div></div></aside>
}

function Drawer({ item, creating=false, onClose, onPrevious, onNext, onDelete, onSave, onCopyToTeam, notify }) {
  const backdrop=useRef(null),shell=useRef(null),closeButton=useRef(null)
  const pendingImageUrls=useRef(new Set())
  const aiGenerationTimer=useRef(null)
  const wheelLocked=useRef(false)
  const [activeImage,setActiveImage]=useState(0)
  const [editing,setEditing]=useState(creating)
  const createDraft=asset=>({name:asset.name,description:asset.description||'',coreScenario:asset.coreScenario||'',targetAudience:asset.targetAudience||'',buyingPointGroups:asset.buyingPointGroups?.length?asset.buyingPointGroups.map(group=>({...group})):asset.sellingPoints?.length?asset.sellingPoints.map((benefit,index)=>({...emptyPopulationTest(index),benefit})):[emptyPopulationTest(0)],images:asset.images||[]})
  const [draft,setDraft]=useState(()=>createDraft(item))
  const [nameError,setNameError]=useState('')
  const [imageError,setImageError]=useState('')
  const [imageDragOver,setImageDragOver]=useState(false)
  const [aiGenerating,setAiGenerating]=useState(false)
  const [promptExpanded,setPromptExpanded]=useState(false)
  const canManage=item.scope==='个人资产'||item.creatorId===currentUserId
  const relatedAttachments=item.relatedAttachments?.length?item.relatedAttachments:[item.previewUrl,...providedImages.filter(url=>url!==item.previewUrl)].filter(Boolean).slice(0,3)
  const displayedImages=editing?draft.images:item.images||[]
  const selectedProductImage=displayedImages[activeImage]
  const shiftProductImage=offset=>setActiveImage(current=>(current+offset+displayedImages.length)%displayedImages.length)
  const handleProductWheel=event=>{if(item.type!=='商品图片'||displayedImages.length<2)return;event.preventDefault();if(wheelLocked.current)return;const delta=Math.abs(event.deltaY)>=Math.abs(event.deltaX)?event.deltaY:event.deltaX;if(Math.abs(delta)<4)return;wheelLocked.current=true;shiftProductImage(delta>0?1:-1);window.setTimeout(()=>{wheelLocked.current=false},260)}
  const selectedProductSpec=imageSpecs[demoImages.indexOf(selectedProductImage)]
  const displayedItem=item.type==='商品图片'&&selectedProductImage?{...item,previewUrl:selectedProductImage,resolution:selectedProductSpec?.[0]||item.resolution,ratio:selectedProductSpec?.[1]}:item
  const close=()=>{if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)return onClose();gsap.to(shell.current,{scale:.99,autoAlpha:0,duration:.18,ease:'power1.in',overwrite:true});gsap.to(backdrop.current,{autoAlpha:0,duration:.2,ease:'power1.in',onComplete:onClose,overwrite:true})}
  useLayoutEffect(()=>{const mm=gsap.matchMedia();mm.add('(prefers-reduced-motion: no-preference)',()=>{gsap.fromTo(backdrop.current,{autoAlpha:0},{autoAlpha:1,duration:.2});gsap.fromTo(shell.current,{autoAlpha:0,scale:.99},{autoAlpha:1,scale:1,duration:.3,ease:'power2.out',clearProps:'transform',onComplete:()=>closeButton.current?.focus()})});mm.add('(prefers-reduced-motion: reduce)',()=>closeButton.current?.focus());return()=>mm.revert()},[])
  useEffect(()=>{const key=e=>{if(e.key==='Escape')close();if(e.key==='ArrowUp')onPrevious?.();if(e.key==='ArrowDown')onNext?.()};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key)},[onPrevious,onNext])
  const discardPendingImages=()=>{pendingImageUrls.current.forEach(url=>URL.revokeObjectURL(url));pendingImageUrls.current.clear()}
  useEffect(()=>{discardPendingImages();if(aiGenerationTimer.current)window.clearTimeout(aiGenerationTimer.current);aiGenerationTimer.current=null;setAiGenerating(false);setActiveImage(0);setEditing(creating);setPromptExpanded(false);setNameError('');setImageError('');setDraft(createDraft(item))},[item.id])
  useEffect(()=>()=>{discardPendingImages();if(aiGenerationTimer.current)window.clearTimeout(aiGenerationTimer.current)},[])
  const cancelEdit=()=>{if(creating){close();return}discardPendingImages();if(aiGenerationTimer.current)window.clearTimeout(aiGenerationTimer.current);aiGenerationTimer.current=null;setAiGenerating(false);setEditing(false);setNameError('');setImageError('');setActiveImage(0);setDraft(createDraft(item))}
  const generateAudienceMarketing=()=>{if(aiGenerating)return;setAiGenerating(true);aiGenerationTimer.current=window.setTimeout(()=>{setDraft(value=>({...value,coreScenario:'高压崩溃场景：职场高压、长期熬夜、焦虑失眠导致的“过劳肥”与情绪失控。\n生理紊乱场景：月经不调、PCOS、备孕困难、顽固性痤疮与脱发。\n代谢停滞场景：节食无效、体重平台期、嗜糖成瘾、饭后极度困倦。',targetAudience:'核心人群：25-40 岁都市女性，特别是被诊断为 PCOS 或处于亚健康高压状态的职业女性与宝妈。\n心理特征：对传统单一减肥法绝望，深受情绪性进食困扰，渴望通过科学成分从根本上解决身体失控感，追求“身心同调”的安全感。',buyingPointGroups:healthBuyingPointGroups.map(group=>({...group}))}));aiGenerationTimer.current=null;setAiGenerating(false);notify('AI 已生成场景、受众与营销组别')},800)}
  const saveEdit=()=>{const name=draft.name.trim();if(!name){setNameError('请输入资产名称');return}const images=draft.images;const buyingPointGroups=draft.buyingPointGroups.map((group,index)=>({...group,group:`营销组别 ${String(index+1).padStart(2,'0')}`,audience:group.audience.trim(),painPoint:group.painPoint.trim(),result:group.result.trim(),feature:group.feature.trim(),benefit:group.benefit.trim(),creative:group.creative.trim()})).filter(group=>group.audience||group.painPoint||group.result||group.feature||group.benefit||group.creative);onSave(item,{name,description:draft.description.trim(),...(item.type==='商品图片'?{coreScenario:draft.coreScenario.trim(),targetAudience:draft.targetAudience.trim(),buyingPointGroups,sellingPoints:buyingPointGroups.map(group=>group.benefit).filter(Boolean),images,imageCount:images.length,previewUrl:images[0]||'',objectImageUrls:[...(item.objectImageUrls||[]),...pendingImageUrls.current]}: {})});pendingImageUrls.current.clear();setEditing(false);setNameError('');setImageError('');notify(creating?'商品已添加':'更改已保存')}
  const addProductImages=event=>{const files=[...(event.dataTransfer?.files||event.target.files||[])];if(!event.dataTransfer)event.target.value='';setImageError('');if(!files.length)return;const invalid=files.find(file=>!file.type.startsWith('image/'));if(invalid){setImageError('仅支持上传图片文件');return}const oversized=files.find(file=>file.size>50*1024*1024);if(oversized){setImageError('单张图片不能超过 50 MB');return}const urls=files.map(file=>URL.createObjectURL(file));urls.forEach(url=>pendingImageUrls.current.add(url));setDraft(value=>({...value,images:[...value.images,...urls]}));setActiveImage(displayedImages.length);notify(`已添加 ${urls.length} 张图片`)}
  const removeProductImage=index=>{const removed=draft.images[index];if(pendingImageUrls.current.has(removed)){URL.revokeObjectURL(removed);pendingImageUrls.current.delete(removed)}const images=draft.images.filter((_,imageIndex)=>imageIndex!==index);setDraft(value=>({...value,images}));setActiveImage(current=>images.length?Math.min(current>index?current-1:current,images.length-1):0);setImageError('');notify('图片已移除')}
  useEffect(()=>{if(!editing)return;const key=event=>{if(event.key==='Escape'){event.stopImmediatePropagation();cancelEdit()}if((event.ctrlKey||event.metaKey)&&event.key==='Enter')saveEdit()};document.addEventListener('keydown',key,true);return()=>document.removeEventListener('keydown',key,true)},[editing,draft,item])
  useEffect(()=>{if(item.type!=='商品图片'||displayedImages.length<2)return;const key=event=>{if(event.key==='ArrowLeft')shiftProductImage(-1);if(event.key==='ArrowRight')shiftProductImage(1)};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key)},[item.type,displayedImages.length])
  return <div ref={backdrop} className="asset-detail-overlay" onMouseDown={e=>e.target===e.currentTarget&&close()}>
    <section ref={shell} className={`asset-detail-shell${item.type==='商品图片'?' product-detail-shell':''}`} role="dialog" aria-modal="true" aria-labelledby="asset-detail-title">
      <div className={`asset-detail-media ${item.type==='商品图片'?'product-gallery-media':''}`}><div className="asset-detail-preview" onWheel={handleProductWheel}>{item.type!=='商品图片'?<Thumb item={item} natural playable/>:selectedProductImage?<Thumb item={displayedItem} natural playable/>:<div className="product-image-empty"><Image/><strong>暂未上传产品图</strong><span>请在右侧商品图片附件中上传图片</span></div>}</div>{item.type==='商品图片'&&displayedImages.length>1&&<><button className="product-gallery-arrow previous" onClick={()=>shiftProductImage(-1)} aria-label="上一张商品图"><ArrowLeft/></button><button className="product-gallery-arrow next" onClick={()=>shiftProductImage(1)} aria-label="下一张商品图"><ArrowRight/></button></>}{item.type==='商品图片'&&displayedImages.length>1&&<div className="product-image-strip" aria-label="商品图片"><span>{displayedImages.length?`${activeImage+1} / ${displayedImages.length}`:'0 / 0'}</span>{displayedImages.map((image,index)=><div className="product-image-item" key={`${image}-${index}`}><button className={`product-image-select ${activeImage===index?'active':''}`} onClick={()=>setActiveImage(index)} aria-label={`查看第 ${index+1} 张商品图`}><img src={image} alt="" loading="lazy" referrerPolicy="no-referrer"/></button></div>)}</div>}</div>
      <nav className="asset-detail-rail" aria-label="详情浏览控制"><button ref={closeButton} onClick={close} aria-label="关闭资产详情"><X/></button>{!creating&&<div><button onClick={onPrevious} aria-label="上一个资产"><ArrowUp/></button><button onClick={onNext} aria-label="下一个资产"><ArrowDown/></button></div>}</nav>
      <aside className={`asset-detail-copy${editing?' is-editing':''}`}>
        {editing?<header className="asset-edit-header"><div><span>{creating?'添加商品':'编辑资产'}</span><h2 id="asset-detail-title">内容与基础信息</h2></div><small>Ctrl / ⌘ + Enter 保存</small></header>:item.group==='作品收藏'?<header className="collection-detail-header"><span>{item.group} / {item.type}</span><h2 id="asset-detail-title" className="collection-inline-edit" contentEditable suppressContentEditableWarning aria-label="编辑作品标题" title="单击编辑标题" onKeyDown={event=>{if(event.key==='Enter'){event.preventDefault();event.currentTarget.blur()}}} onBlur={event=>{const name=event.currentTarget.textContent.trim();if(!name){event.currentTarget.textContent=item.name;return}if(name!==item.name){onSave(item,{name});notify('作品标题已保存')}}}>{item.name}</h2><p className="collection-inline-edit" contentEditable suppressContentEditableWarning aria-label="编辑作品描述" title="单击编辑描述" onBlur={event=>{const description=event.currentTarget.innerText.trim();if(description!==item.description){onSave(item,{description});notify('作品描述已保存')}}}>{item.description}</p></header>:item.group==='素材库'?<header className="collection-detail-header"><span>{item.group} / {isVideo(item)?'视频素材':'图片素材'}</span><h2 id="asset-detail-title" className={canManage?'collection-inline-edit':undefined} contentEditable={canManage?'plaintext-only':false} suppressContentEditableWarning aria-label={canManage?'编辑素材标题':undefined} title={canManage?'单击编辑标题，点击其他位置自动保存':undefined} onKeyDown={event=>{event.stopPropagation();if(event.nativeEvent.isComposing)return;if(event.key==='Enter'){event.preventDefault();event.currentTarget.blur()}if(event.key==='Escape'){event.preventDefault();event.currentTarget.textContent=item.name;event.currentTarget.blur()}}} onBlur={event=>{if(!canManage)return;const name=event.currentTarget.textContent.trim();event.currentTarget.textContent=name||item.name;if(!name){notify('标题不能为空，已恢复原标题');return}if(name!==item.name){onSave(item,{name});notify('素材标题已保存')}}}>{item.name}</h2></header>:<header><h2 id="asset-detail-title">{item.name}</h2><div className="asset-detail-meta-tags" aria-label="资产归属"><span><Users aria-hidden="true"/>{item.scope}</span></div></header>}
        <div className="asset-detail-copy-scroll">
          {editing&&<form className="asset-edit-form" onSubmit={event=>{event.preventDefault();saveEdit()}}>
            <div className="asset-edit-module"><header className="asset-edit-module-header"><span><Package aria-hidden="true"/></span><div><strong>{item.type==='商品图片'?'商品基础信息':'资产基础信息'}</strong><small>名称与内容描述</small></div></header><div className="asset-edit-module-fields"><section><label htmlFor="asset-edit-name">资产名称</label><input id="asset-edit-name" autoFocus value={draft.name} onChange={event=>{setDraft(value=>({...value,name:event.target.value}));setNameError('')}} aria-invalid={Boolean(nameError)} aria-describedby={nameError?'asset-name-error':undefined}/>{nameError&&<small id="asset-name-error" className="field-error">{nameError}</small>}</section>{item.type==='商品图片'&&<section className="product-attachment-field"><label htmlFor="product-attachment-upload">商品图片附件</label><div className="product-image-strip product-attachment-list is-editing" aria-label="商品图片附件">{draft.images.map((image,index)=><div className="product-image-item" key={`${image}-${index}`}><button type="button" className={`product-image-select ${activeImage===index?'active':''}`} onClick={()=>setActiveImage(index)} aria-label={`预览附件 ${index+1}`}><img src={image} alt="" loading="lazy" referrerPolicy="no-referrer"/></button><button type="button" className="product-image-remove" onClick={()=>removeProductImage(index)} aria-label={`删除第 ${index+1} 张商品图`}><X/></button></div>)}<label className={`product-image-upload${draft.images.length?'':' product-upload-empty'}${imageDragOver?' is-drag-over':''}`} onDragOver={event=>{event.preventDefault();setImageDragOver(true)}} onDragLeave={event=>{if(!event.currentTarget.contains(event.relatedTarget))setImageDragOver(false)}} onDrop={event=>{event.preventDefault();setImageDragOver(false);addProductImages(event)}}><input id="product-attachment-upload" type="file" accept="image/*" multiple onChange={addProductImages}/><Upload/>{draft.images.length?<span>上传</span>:<div><strong>点击选择文件</strong><span>或将文件拖放到这里</span></div>}</label></div><small>支持多张图片，单张不超过 50 MB；点击附件同步预览。</small>{imageError&&<small className="field-error" role="alert">{imageError}</small>}</section>}<section><label htmlFor="asset-edit-description">{item.type==='商品图片'?'商品描述':'资产描述'}</label><textarea id="asset-edit-description" className="asset-description-input" value={draft.description} onChange={event=>setDraft(value=>({...value,description:event.target.value}))} placeholder={item.type==='商品图片'?'补充商品介绍或说明':'补充这项资产的用途或说明'}/></section></div></div>
            {item.type==='商品图片'&&<><div className="asset-ai-actions asset-ai-generation-bridge"><button type="button" className="asset-ai-generate" onClick={generateAudienceMarketing} disabled={aiGenerating} title="生成场景、受众与营销组别"><Sparkles aria-hidden="true"/>{aiGenerating?'生成中…':'AI 生成'}</button><span>以下内容可以使用AI生成</span></div><div className="asset-edit-module"><header className="asset-edit-module-header"><span><SlidersHorizontal aria-hidden="true"/></span><div><strong>场景与受众定位</strong><small>AI 生成后可继续编辑</small></div></header><div className="asset-edit-module-fields"><section><label htmlFor="asset-edit-scenario">核心场景</label><textarea id="asset-edit-scenario" className="asset-product-textarea" value={draft.coreScenario} onChange={event=>setDraft(value=>({...value,coreScenario:event.target.value}))} placeholder="描述产品最主要的使用场景"/></section><section><label htmlFor="asset-edit-audience">目标受众</label><textarea id="asset-edit-audience" className="asset-product-textarea" value={draft.targetAudience} onChange={event=>setDraft(value=>({...value,targetAudience:event.target.value}))} placeholder="描述核心用户特征与需求"/></section></div></div><PopulationTestsEditor groups={draft.buyingPointGroups} onChange={buyingPointGroups=>setDraft(value=>({...value,buyingPointGroups}))}/></>}
          </form>}
          {!editing&&<>
          {item.group==='作品收藏'&&<><section className="detail-section"><h3>基础信息</h3><dl><div><dt>归属</dt><dd>{item.scope}</dd></div></dl></section><section className="detail-section"><h3>关联与生成信息</h3><dl><div><dt>任务 ID</dt><dd><code>{item.taskId}</code></dd></div><div><dt>模型</dt><dd>{item.model}</dd></div><div><dt>技能</dt><dd>{item.skill}</dd></div><div className="detail-attachments"><dt>相关附件</dt><dd><RelatedAttachments attachments={relatedAttachments}/></dd></div><div className="detail-prompt"><dt>提示词</dt><dd><PromptContent prompt={item.prompt} attachments={relatedAttachments} expanded={promptExpanded} onToggle={()=>setPromptExpanded(value=>!value)}/></dd></div></dl></section><section className="detail-section"><h3>媒体属性</h3><dl><div><dt>画面比例</dt><dd>{item.ratio}</dd></div><div><dt>分辨率</dt><dd>{item.resolution}</dd></div><div><dt>文件类型</dt><dd>{item.fileType}</dd></div><div><dt>文件大小</dt><dd>{item.fileSize}</dd></div></dl></section></>}
          {item.group==='素材库'&&<><section className="detail-section"><h3>基础信息</h3><dl><div><dt>资产 ID</dt><dd><code>{item.id}</code></dd></div>{item.scope==='团队资产'&&<div><dt>来源</dt><dd>{item.source}</dd></div>}<div><dt>归属</dt><dd>{item.scope}</dd></div></dl></section><section className="detail-section"><h3>媒体属性</h3><dl>{isVideo(item)?<><div><dt>画面比例</dt><dd>{item.ratio}</dd></div><div><dt>清晰度</dt><dd>{item.clarity}</dd></div><div><dt>时长</dt><dd>{item.duration}</dd></div></>:<><div><dt>画面比例</dt><dd>{item.ratio}</dd></div><div><dt>分辨率</dt><dd>{item.resolution}</dd></div></>}<div><dt>文件类型</dt><dd>{item.fileType}</dd></div><div><dt>文件大小</dt><dd>{item.fileSize}</dd></div></dl></section></>}
          {item.type==='商品图片'&&<ProductDetails item={item}/>}
          {item.scope==='团队资产'&&<section className="detail-section"><h3>成员权限</h3><dl><div><dt>查看与创建</dt><dd>团队成员</dd></div><div><dt>修改与删除</dt><dd>{canManage?'你是创建者':'仅创建者'}</dd></div></dl></section>}
          </>}
        </div>
        <div className={`asset-detail-actions${editing?' edit-actions':''}`}>{editing?<><button type="button" onClick={cancelEdit}><X/>取消</button><button type="button" className="save-action" onClick={saveEdit}><Check/>{creating?'添加商品':'保存更改'}</button></>:<>{item.group==='作品收藏'?<button onClick={()=>notify('做同款功能待接入')}><Sparkles/>做同款</button>:item.scope==='个人资产'&&['素材库','商品资产'].includes(item.group)?<button onClick={()=>onCopyToTeam(item)}><Users/>复制到团队</button>:item.type!=='商品图片'&&<><button onClick={()=>notify('资产已开始下载')}><Download/>下载</button><button onClick={()=>notify('已复制资产链接')}><Link2/>复制链接</button></>}{canManage&&item.type==='商品图片'&&<button onClick={()=>setEditing(true)}><Pencil/>编辑</button>}{canManage&&<button className="danger-action" onClick={()=>onDelete(item)}><Trash2/>删除</button>}</>}</div>
      </aside>
    </section>
  </div>
}

function AssetCard({ item, selected, onOpen, onToggle, notify }) {
  return <article className={`asset-card ${selected?'selected':''}`}>
    <button className="asset-open" onClick={onOpen} aria-label={`查看${item.name}详情`}/>
    <div className="asset-media"><Thumb item={item}/><button className="asset-check" onClick={onToggle} aria-label={`选择${item.name}`}>{selected&&<Check/>}</button><button className="asset-more" onClick={()=>notify(`已打开“${item.name}”操作菜单`)} aria-label={`更多操作：${item.name}`}><MoreHorizontal/></button></div>
    <div className="asset-info compact"><strong>{item.name}</strong><p className={item.scope==='个人资产'?'personal-asset-meta':undefined}>{item.scope==='团队资产'&&<span className="asset-source-name"><b className={`source-avatar ${sourceAvatarColor(item.source)}`} aria-hidden="true">{item.source.slice(0,1)}</b>{item.source}</span>}<time>{item.date}</time></p></div>
  </article>
}

export default function AssetWorkspace() {
  const [assetItems,setAssetItems]=useState(assets),[scope,setScope]=useState('个人资产'),[group,setGroup]=useState('全部资产'),[query,setQuery]=useState(''),[type,setType]=useState('全部类型'),[view,setView]=useState('grid'),[selected,setSelected]=useState([]),[detail,setDetail]=useState(null),[upload,setUpload]=useState(false),[uploadFile,setUploadFile]=useState(null),[uploadError,setUploadError]=useState(''),[uploading,setUploading]=useState(false),[deleteTargets,setDeleteTargets]=useState([]),[toast,setToast]=useState('')
  const [newProduct,setNewProduct]=useState(null)
  const openCreateProduct=()=>setNewProduct({id:`product_${Date.now()}`,name:'',description:'',type:'商品图片',group:'商品资产',scope,source:'林屿',creatorId:currentUserId,date:'刚刚',images:[],imageCount:0,previewUrl:'',coreScenario:'',targetAudience:'',buyingPointGroups:[emptyPopulationTest(0)]})
  const uploadCloseButton=useRef(null)
  const deleteConfirmButton=useRef(null)
  const filtered=useMemo(()=>assetItems.filter(item=>item.scope===scope&&(group==='全部资产'||item.group===group)&&(type==='全部类型'||item.type===type)&&(item.name.includes(query)||item.id.includes(query))),[assetItems,scope,group,type,query])
  const filteredIds=filtered.map(item=>item.id)
  const allFilteredSelected=filteredIds.length>0&&filteredIds.every(id=>selected.includes(id))
  const detailIndex=detail?filtered.findIndex(item=>item.id===detail.id):-1
  const showRelative=offset=>{if(!filtered.length)return;setDetail(filtered[(detailIndex+offset+filtered.length)%filtered.length])}
  const canDeleteSelection=selected.every(id=>assetItems.find(item=>item.id===id)?.creatorId===currentUserId)
  const canCopySelection=scope==='个人资产'&&selected.every(id=>['素材库','商品资产'].includes(assetItems.find(item=>item.id===id)?.group))
  useEffect(()=>{setSelected([]);setType('全部类型');setDetail(null)},[scope])
  useEffect(()=>{setSelected([]);setType('全部类型');setDetail(null)},[group])
  const notify=message=>{setToast(message);window.setTimeout(()=>setToast(''),2200)}
  const toggle=id=>setSelected(items=>items.includes(id)?items.filter(item=>item!==id):[...items,id])
  const toggleAll=()=>setSelected(items=>allFilteredSelected?items.filter(id=>!filteredIds.includes(id)):[...new Set([...items,...filteredIds])])
  const copyToTeam=ids=>{const selectedItems=assetItems.filter(item=>ids.includes(item.id)&&item.scope==='个人资产'&&['素材库','商品资产'].includes(item.group));if(!selectedItems.length)return;const copied=selectedItems.map((item,index)=>({...item,id:`${item.id}_team_${Date.now()}_${index}`,scope:'团队资产',date:'刚刚',creatorId:currentUserId,objectUrl:undefined,objectImageUrls:undefined}));setAssetItems(items=>[...copied,...items]);notify(`复制到团队成功，共 ${copied.length} 项`)}
  const types=group==='素材库'?['全部类型','图片','视频']:group==='作品收藏'?['全部类型','图片作品','视频作品']:group==='商品资产'?['商品图片']:scope==='个人资产'?['全部类型','图片','视频','图片作品','视频作品','商品图片']:['全部类型','图片','视频','商品图片']
  const typeIcons={'全部类型':LayoutGrid,'图片':Image,'视频':Film,'图片作品':GalleryVerticalEnd,'视频作品':Film,'商品图片':Package,'营销报告':FileBarChart}
  const chooseFile=event=>{const file=event.target.files?.[0];setUploadError('');setUploadFile(null);if(!file)return;const isImageFile=file.type.startsWith('image/'),isVideoFile=file.type.startsWith('video/');if(!isImageFile&&!isVideoFile)return setUploadError('仅支持图片或视频文件。');if(isImageFile&&file.size>50*1024*1024)return setUploadError('图片超过 50 MB，请压缩后重试。');if(isVideoFile&&file.size>2*1024*1024*1024)return setUploadError('视频超过 2 GB，请压缩后重试。');setUploadFile(file)}
  const submitUpload=()=>{if(!uploadFile||uploading)return;setUploading(true);window.setTimeout(()=>{const isVideoFile=uploadFile.type.startsWith('video/'),url=URL.createObjectURL(uploadFile),fileSize=uploadFile.size>=1024*1024?`${(uploadFile.size/1024/1024).toFixed(1)} MB`:`${Math.ceil(uploadFile.size/1024)} KB`;const newAsset={id:`asset_${Date.now()}`,name:uploadFile.name.replace(/\.[^.]+$/,''),description:'用户上传的资产。',type:isVideoFile?'视频':'图片',group:'素材库',scope,source:'林屿',url,previewUrl:isVideoFile?'':url,ratio:isVideoFile?'16:9':'1:1',resolution:isVideoFile?undefined:'原始尺寸',clarity:isVideoFile?'原始':undefined,duration:isVideoFile?'--:--':undefined,fileType:(uploadFile.name.split('.').pop()||'文件').toUpperCase(),fileSize,tone:isVideoFile?'night':'ocean',date:'刚刚',creatorId:currentUserId,objectUrl:url};setAssetItems(items=>[newAsset,...items]);setUploading(false);setUpload(false);setUploadFile(null);setGroup('素材库');setType(isVideoFile?'视频':'图片');notify('资产已添加到素材库')},700)}
  const closeUpload=()=>{if(uploading)return;setUpload(false);setUploadFile(null);setUploadError('')}
  const requestDelete=items=>{setDeleteTargets(Array.isArray(items)?items:[items]);setDetail(null)}
  const confirmDelete=()=>{const ids=new Set(deleteTargets.map(item=>item.id));deleteTargets.forEach(item=>{item.objectUrl&&URL.revokeObjectURL(item.objectUrl);item.objectImageUrls?.forEach(url=>URL.revokeObjectURL(url))});setAssetItems(items=>items.filter(item=>!ids.has(item.id)));setSelected(items=>items.filter(id=>!ids.has(id)));setDeleteTargets([]);notify(ids.size===1?'删除成功':'删除成功，共删除 '+ids.size+' 项')}
  useEffect(()=>{if(!upload)return;uploadCloseButton.current?.focus();const closeOnEscape=event=>{if(event.key==='Escape')closeUpload()};document.addEventListener('keydown',closeOnEscape);return()=>document.removeEventListener('keydown',closeOnEscape)},[upload,uploading])
  useEffect(()=>{if(!deleteTargets.length)return;deleteConfirmButton.current?.focus();const closeOnEscape=event=>{if(event.key==='Escape')setDeleteTargets([])};document.addEventListener('keydown',closeOnEscape);return()=>document.removeEventListener('keydown',closeOnEscape)},[deleteTargets])

  return <>
    <Sidebar items={assetItems} {...{scope,setScope,group,setGroup}}/>
    <main className="asset-main">
      <div className="asset-sticky-head">
        <header className="asset-compact-header"><div className="asset-breadcrumb">资产管理 <ChevronRight/> {scope}</div><div><h1 id="asset-page-title">{group}</h1><p>集中整理、查询和复用你的创作素材与生成作品。</p></div></header>
        <section className={`asset-toolbar ${group==='商品资产'?'without-type-tabs':''}`}>{group!=='商品资产'&&<div className="asset-type-tabs" role="group" aria-label="筛选资产类型">{types.map(name=>{const Icon=typeIcons[name];return <button key={name} className={type===name?'active':''} onClick={()=>setType(name)} aria-pressed={type===name}><Icon/>{name==='全部类型'?'全部':name}</button>})}</div>}<label className="asset-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索名称或资产 ID" aria-label="搜索资产"/>{query&&<button onClick={()=>setQuery('')} aria-label="清空搜索"><X/></button>}</label><div className="toolbar-actions"><button className="toolbar-select-all" onClick={toggleAll} aria-pressed={allFilteredSelected} disabled={!filtered.length}>{allFilteredSelected?'取消全选':'全选'}</button><div className="view-switch"><button className={view==='grid'?'active':''} onClick={()=>setView('grid')} aria-label="网格视图"><Grid2X2/></button><button className={view==='list'?'active':''} onClick={()=>setView('list')} aria-label="列表视图"><List/></button></div>{(group==='素材库'||group==='商品资产')&&<button className="page-primary toolbar-upload" onClick={()=>group==='商品资产'?openCreateProduct():setUpload(true)}>{group==='商品资产'?<Package/>:<Upload/>}{group==='商品资产'?'添加商品':'上传资产'}</button>}</div></section>
        <div className="asset-summary"><span>共 {filtered.length} 项</span></div>
      </div>
      {filtered.length?<section className={`asset-collection ${view}`}>{filtered.map(item=><AssetCard key={item.id} item={item} selected={selected.includes(item.id)} onOpen={()=>setDetail(item)} onToggle={()=>toggle(item.id)} notify={notify}/>)}</section>:<section className="asset-empty"><Search/><h2>没有找到匹配的资产</h2><p>尝试更换关键词或筛选条件。</p><button onClick={()=>{setQuery('');setType('全部类型')}}>清除筛选</button></section>}
      {selected.length>0&&<div className="selection-bar"><span><b>{selected.length}</b> 项已选择</span>{canCopySelection&&<button onClick={()=>{copyToTeam(selected);setSelected([])}}><Users/>复制到团队</button>}{canDeleteSelection&&<button onClick={()=>requestDelete(assetItems.filter(item=>selected.includes(item.id)))}><Trash2/>删除</button>}<button className="selection-close" onClick={()=>setSelected([])} aria-label="取消选择"><X/></button></div>}
      {detail&&<Drawer item={detail} onClose={()=>setDetail(null)} onPrevious={()=>showRelative(-1)} onNext={()=>showRelative(1)} onDelete={requestDelete} onCopyToTeam={item=>copyToTeam([item.id])} onSave={(current,patch)=>{setAssetItems(items=>items.map(item=>item.id===current.id?{...item,...patch}:item));setDetail(value=>value?.id===current.id?{...value,...patch}:value)}} notify={notify}/>}
      {newProduct&&<Drawer item={newProduct} creating onClose={()=>setNewProduct(null)} onSave={(current,patch)=>{setAssetItems(items=>[{...current,...patch},...items]);setNewProduct(null);setQuery('');setType('全部类型')}} notify={notify}/>}
      {upload&&<div className="dialog-backdrop" onMouseDown={e=>e.target===e.currentTarget&&closeUpload()}><section className="upload-dialog" role="dialog" aria-modal="true" aria-labelledby="upload-title"><header><div><h2 id="upload-title">上传到素材库</h2><p>支持图片与视频，上传后遵循当前资产归属权限。</p></div><button ref={uploadCloseButton} onClick={closeUpload} disabled={uploading} aria-label="关闭上传窗口"><X/></button></header><label className={`upload-drop ${uploadError?'error':''}`}><input type="file" accept="image/*,video/*" onChange={chooseFile}/><Upload/><strong>{uploadFile?.name||'选择文件上传'}</strong><span>{uploadError||'图片最大 50 MB，视频最大 2 GB'}</span></label><footer><button className="cancel" onClick={closeUpload} disabled={uploading}>取消</button><button className="confirm" onClick={submitUpload} disabled={!uploadFile||uploading}>{uploading?'上传中…':'添加资产'}</button></footer></section></div>}
      {deleteTargets.length>0&&<div className="dialog-backdrop" onMouseDown={event=>event.target===event.currentTarget&&setDeleteTargets([])}><section className="upload-dialog delete-dialog" role="alertdialog" aria-modal="true" aria-labelledby="delete-title" aria-describedby="delete-description"><header><div><h2 id="delete-title">确认删除资产？</h2><p id="delete-description">{deleteTargets.length===1?`“${deleteTargets[0].name}”将从资产列表中删除。`:`所选 ${deleteTargets.length} 项资产将从列表中删除。`}</p></div><button onClick={()=>setDeleteTargets([])} aria-label="关闭删除确认"><X/></button></header><footer><button className="cancel" onClick={()=>setDeleteTargets([])}>取消</button><button ref={deleteConfirmButton} className="confirm danger-confirm" onClick={confirmDelete}><Trash2/>确认删除</button></footer></section></div>}
      {toast&&<div className="asset-toast" role="status"><Check/>{toast}</div>}
    </main>
  </>
}
