import React, { useEffect, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { ArrowUp, Bot, Check, ChevronDown, Copy, FileText, GalleryVerticalEnd, Image, LogOut, MessageSquareText, MoreHorizontal, Paperclip, Pencil, Pin, Play, Plus, RotateCcw, Search, Sparkles, Square, Trash2, Video, WandSparkles } from 'lucide-react'
import { asCssVariables, lightColors } from './color-tokens'
import './design-system.css'
import './index.css'
import AssetWorkspace, { mockPreviewImages } from './AssetWorkspace'
import AgentPromptComposer from './AgentPromptComposer'
import VideoWorkspace from './VideoWorkspace'

const navigation=[['agent','\ue62a','Agent'],['video','\ue6a7','视频'],['canvas','\ue8e7','画布'],['skills','\ue95f','技能'],['assets','\ue552','资产'],['history','\ue685','历史']]
const pages={agent:['Agent','创建、配置并运行你的智能 Agent。','还没有 Agent','新建 Agent'],canvas:['画布','在可视化画布中组织想法与工作流。','还没有画布','新建画布'],skills:['技能','管理 Agent 可调用的技能和能力。','还没有技能','新建技能'],history:['历史','查看最近执行记录与工作历史。','暂无历史记录',null]}
const pageFromHash=()=>{const id=window.location.hash.replace(/^#\/?/,'');return id==='assets'||id==='video'||pages[id]?id:'video'}
function FontIcon({glyph}){return <span className="agent-font-icon" aria-hidden="true">{glyph}</span>}
function DirectorySidebar({active,onSelect}){const [open,setOpen]=useState(false),ref=useRef(null);useEffect(()=>{if(!open)return;const close=e=>!ref.current?.contains(e.target)&&setOpen(false);document.addEventListener('pointerdown',close);return()=>document.removeEventListener('pointerdown',close)},[open]);return <aside className="directory-sidebar collapsed" aria-label="主目录"><div className="directory-brand"><span className="wordmark">ShuLan</span></div><nav className="directory-navigation">{navigation.map(([id,glyph,label])=><button key={id} className={active===id?'active':''} onClick={()=>onSelect(id)} title={label}><FontIcon glyph={glyph}/><span>{label}</span></button>)}</nav><div className="directory-footer"><div className="user-card" ref={ref}><button className="user-avatar" onClick={()=>setOpen(v=>!v)} aria-label="查看成员信息">林</button>{open&&<div className="member-popover"><div className="member-popover-head"><div className="member-avatar-large">林</div><div><strong>林屿</strong><span>企业成员</span></div></div><dl><div><dt>用户 ID</dt><dd>user_1024</dd></div><div><dt>所属公司</dt><dd>澄明科技有限公司</dd></div></dl><button className="member-logout"><LogOut/>退出当前账号</button></div>}</div></div></aside>}
function PlaceholderPanel(){return <section className="conversation-panel"><div className="placeholder-copy"><GalleryVerticalEnd/><strong>会话侧边栏</strong><span>内容暂时搁置</span></div></section>}
function ContentPage({pageId}){const [title,description,empty,action]=pages[pageId];return <main className="content-panel page-content"><header className="page-header"><div><h1>{title}</h1><p>{description}</p></div>{action&&<button className="page-primary"><Plus/>{action}</button>}</header><section className="page-empty"><span className="page-empty-icon"><GalleryVerticalEnd/></span><h2>{empty}</h2><p>{action?`点击“${action}”开始使用。`:'完成的任务和操作记录会显示在这里。'}</p></section></main>}
const seedConversations=[
  {id:1,title:'好的！这是一个简洁的 Prisma…',type:'agent',meta:'Agent 对话',time:'10:45',pinned:false},
  {id:2,title:'气泡水品牌发布短片',type:'video',meta:'视频生成',time:'10:45',thumbnail:mockPreviewImages[0],pinned:false},
  {id:3,title:'夏日主视觉候选方案',type:'image',meta:'图片生成',time:'昨天',thumbnail:mockPreviewImages[1],pinned:false},
  {id:4,title:'产品镜头节奏调整',type:'video',meta:'视频生成',time:'昨天',thumbnail:mockPreviewImages[2],pinned:false},
  {id:5,title:'组件库发布流程建议',type:'agent',meta:'Agent 对话',time:'周一',pinned:false},
  {id:6,title:'品牌色彩方向探索',type:'image',meta:'图片生成',time:'周一',thumbnail:mockPreviewImages[3],pinned:false},
  {id:7,title:'设计规范检查结果',type:'agent',meta:'Agent 对话',time:'上周',pinned:false},
  {id:8,title:'竖屏人物视觉提案',type:'image',meta:'图片生成',time:'上周',thumbnail:mockPreviewImages[4],pinned:false},
  {id:9,title:'饮品礼盒开箱动画',type:'video',meta:'视频生成',time:'8 月 28 日',thumbnail:mockPreviewImages[5],pinned:false},
  {id:10,title:'东方美学人物海报',type:'image',meta:'图片生成',time:'8 月 27 日',thumbnail:mockPreviewImages[6],pinned:false},
  {id:11,title:'营销活动文案整理',type:'agent',meta:'Agent 对话',time:'8 月 26 日',pinned:false},
  {id:12,title:'品牌动态视觉 03',type:'video',meta:'视频生成',time:'8 月 25 日',thumbnail:mockPreviewImages[7],pinned:false},
  {id:13,title:'产品场景图候选',type:'image',meta:'图片生成',time:'8 月 24 日',thumbnail:mockPreviewImages[8],pinned:false},
  {id:14,title:'新品发布节奏建议',type:'agent',meta:'Agent 对话',time:'8 月 23 日',pinned:false},
  {id:15,title:'社交媒体短片版本',type:'video',meta:'视频生成',time:'8 月 22 日',thumbnail:mockPreviewImages[9],pinned:false},
  {id:16,title:'秋季新品主视觉方案',type:'image',meta:'图片生成',time:'8 月 21 日',thumbnail:mockPreviewImages[0],pinned:false},
  {id:17,title:'产品卖点文案优化',type:'agent',meta:'Agent 对话',time:'8 月 20 日',pinned:false},
  {id:18,title:'城市夜景宣传短片',type:'video',meta:'视频生成',time:'8 月 19 日',thumbnail:mockPreviewImages[1],pinned:false},
  {id:19,title:'会员活动海报设计',type:'image',meta:'图片生成',time:'8 月 18 日',thumbnail:mockPreviewImages[2],pinned:false},
  {id:20,title:'发布会流程内容整理',type:'agent',meta:'Agent 对话',time:'8 月 17 日',pinned:false},
  {id:21,title:'咖啡新品开箱动画',type:'video',meta:'视频生成',time:'8 月 16 日',thumbnail:mockPreviewImages[3],pinned:false},
  {id:22,title:'节日礼盒场景效果图',type:'image',meta:'图片生成',time:'8 月 15 日',thumbnail:mockPreviewImages[4],pinned:false},
  {id:23,title:'用户反馈要点总结',type:'agent',meta:'Agent 对话',time:'8 月 14 日',pinned:false},
  {id:24,title:'新品功能演示短片',type:'video',meta:'视频生成',time:'8 月 13 日',thumbnail:mockPreviewImages[5],pinned:false},
  {id:25,title:'社交平台封面候选',type:'image',meta:'图片生成',time:'8 月 12 日',thumbnail:mockPreviewImages[6],pinned:false}
]
function ConversationIcon({item}){return item.thumbnail?<><img src={item.thumbnail} alt=""/>{item.type==='video'&&<i className="thumbnail-play" aria-hidden="true"><Play/></i>}</>:item.type==='image'?<Image/>:item.type==='video'?<Video/>:<Bot/>}
function ConversationSidebar({items,selected,onSelect,onNew,onUpdate,onDelete}){const [query,setQuery]=useState('');const [menuId,setMenuId]=useState(null);const [renaming,setRenaming]=useState(null);const [draft,setDraft]=useState('');const menuRef=useRef(null);useEffect(()=>{if(menuId===null)return;const close=event=>!menuRef.current?.contains(event.target)&&setMenuId(null);document.addEventListener('pointerdown',close);return()=>document.removeEventListener('pointerdown',close)},[menuId]);const beginRename=item=>{setRenaming(item.id);setDraft(item.title);setMenuId(null)};const finishRename=id=>{const title=draft.trim();if(title)onUpdate(id,{title});setRenaming(null)};const shown=items.filter(item=>item.title.includes(query)||item.meta.includes(query));const pinned=shown.filter(item=>item.pinned);const regular=shown.filter(item=>!item.pinned);const renderItem=item=><article className={selected===item.id?'active':''} key={item.id}><button className="conversation-main" onClick={()=>onSelect(item.id)}><span className={`conversation-icon ${item.thumbnail?'has-thumbnail':''}`}><ConversationIcon item={item}/></span><span>{renaming===item.id?<input autoFocus value={draft} onChange={event=>setDraft(event.target.value)} onClick={event=>event.stopPropagation()} onBlur={()=>finishRename(item.id)} onKeyDown={event=>{if(event.key==='Enter')finishRename(item.id);if(event.key==='Escape')setRenaming(null)}} aria-label="重命名创作记录"/>:<b>{item.pinned&&<Pin/>}{item.title}</b>}<small>{item.meta} <i/> {item.time}</small></span></button><button className="conversation-more" onClick={event=>{event.stopPropagation();setMenuId(menuId===item.id?null:item.id)}} aria-label={`${item.title}更多操作`}><MoreHorizontal/></button>{menuId===item.id&&<div className="conversation-menu" ref={menuRef}><button onClick={()=>{onUpdate(item.id,{pinned:!item.pinned});setMenuId(null)}}><Pin/>{item.pinned?'取消置顶':'置顶'}</button><button onClick={()=>beginRename(item)}><Pencil/>重命名</button><button className="danger" onClick={()=>{onDelete(item.id);setMenuId(null)}}><Trash2/>删除</button></div>}</article>;return <aside className="conversation-panel agent-conversations" aria-label="创作记录"><header><strong>创作记录</strong></header><button className="history-new" onClick={onNew}><Plus/>新增对话</button><label className="conversation-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索对话框" aria-label="搜索创作记录"/></label><div className="conversation-fixed"><button className={`conversation-default ${selected===null?'active':''}`} onClick={onNew}><span className="conversation-icon"><MessageSquareText/></span><span><b>默认对话</b><small>Agent 对话 <i/> 10:45</small></span><MoreHorizontal/></button>{pinned.map(renderItem)}</div><div className="conversation-list">{regular.map(renderItem)}{!shown.length&&<div className="conversation-empty">没有匹配的创作记录</div>}</div></aside>}
function AgentComposer({onSend,running}){return <AgentPromptComposer onSend={onSend} running={running}/>}
function Welcome({onSuggestion}){return <section className="agent-welcome"><span className="welcome-mark"><WandSparkles/></span><h2>今天想完成什么？</h2><p>描述目标即可，我会拆解任务、调用合适的能力并整合结果。</p><div className="agent-suggestions"><button onClick={()=>onSuggestion('为新品气泡水设计一套发布内容，包括文案、主视觉和短视频。')}><Image/><span><b>创建发布内容</b><small>文案、主视觉与短视频</small></span></button><button onClick={()=>onSuggestion('总结这份产品需求并整理下一步行动项。')}><FileText/><span><b>整理产品需求</b><small>摘要、风险与行动项</small></span></button></div></section>}
function OutputActions({onNotice}){return <div className="output-actions"><button onClick={()=>onNotice('已再次生成')}><RotateCcw/>再次生成</button><button onClick={()=>onNotice('结果已复制')}><Copy/>复制</button><button onClick={()=>onNotice('删除前需要确认')}><Trash2/>删除</button><time><Check/>刚刚</time></div>}
function ConversationFlow({messages,running,onNotice}){return <div className="agent-flow">{messages.map((message,index)=>message.role==='user'?<div className="agent-message user-message" key={index}><div className="user-prompt">{message.text}</div><span className="message-avatar user-avatar">林</span></div>:<div className="agent-message assistant-message" key={index}><span className="message-avatar assistant-avatar"><Bot/></span><div className="assistant-content"><div className="output-label"><MessageSquareText/>整合输出</div><p>我已将任务拆成品牌文案、主视觉和短视频三个部分，并保持“轻盈、清爽、充满活力”的统一方向。</p><blockquote>打开这一刻，让清爽气泡点亮整个夏天。</blockquote><div className="output-plan"><div><span><Check/></span><p><b>品牌文案</b><small>主标题、卖点与社交媒体短文案</small></p></div><div><span><Image/></span><p><b>主视觉</b><small>薄荷绿渐变空间 · 3 个候选比例</small></p><em>3 张图片</em></div><div><span><Video/></span><p><b>短视频</b><small>8 秒产品镜头 · 1080P</small></p><em>生成就绪</em></div></div><OutputActions onNotice={onNotice}/></div></div>)}{running&&<div className="agent-message assistant-message"><span className="message-avatar assistant-avatar"><Bot/></span><div className="agent-thinking"><i/><i/><i/><span>正在理解目标并组织输出…</span></div></div>}</div>}
function AgentWorkspace(){const [items,setItems]=useState(seedConversations);const [selected,setSelected]=useState(null);const [messages,setMessages]=useState([]);const [running,setRunning]=useState(false);const [notice,setNotice]=useState('');const timer=useRef(null);useEffect(()=>()=>clearTimeout(timer.current),[]);const notify=text=>{setNotice(text);window.setTimeout(()=>setNotice(''),1600)};const send=text=>{if(running){clearTimeout(timer.current);setRunning(false);notify('已停止生成');return}if(!text)return;setMessages(value=>[...value,{role:'user',text}]);setRunning(true);timer.current=window.setTimeout(()=>{setMessages(value=>[...value,{role:'agent'}]);setRunning(false);if(!selected){const id=Date.now();setSelected(id);setItems(value=>[{id,title:text.slice(0,16),type:'agent',meta:'Agent 对话',time:'刚刚',pinned:false},...value])}},1100)};const startNew=()=>{clearTimeout(timer.current);setRunning(false);setSelected(null);setMessages([])};const choose=id=>{setSelected(id);setMessages([{role:'user',text:id===1?'为新品气泡水设计一套发布内容，包括文案、主视觉和短视频。':'请继续处理这个任务。'},{role:'agent'}])};const updateItem=(id,patch)=>setItems(value=>{const current=value.find(item=>item.id===id);if(!current)return value;const updated={...current,...patch};return patch.pinned===true?[updated,...value.filter(item=>item.id!==id)]:value.map(item=>item.id===id?updated:item)});const deleteItem=id=>{setItems(value=>value.filter(item=>item.id!==id));if(selected===id)startNew();notify('创作记录已删除')};return <><ConversationSidebar items={items} selected={selected} onSelect={choose} onNew={startNew} onUpdate={updateItem} onDelete={deleteItem}/><main className="agent-workspace"><header className="agent-workspace-header"><div><span className="assistant-avatar"><Bot/></span><div><h1>ShuLan Agent</h1><p>多模态创作助手 · 自动规划与执行</p></div></div><button><Sparkles/>能力配置</button></header><div className={`agent-stage ${messages.length?'has-messages':''}`}>{messages.length?<ConversationFlow messages={messages} running={running} onNotice={notify}/>:<Welcome onSuggestion={send}/>}<AgentComposer onSend={send} running={running}/></div>{notice&&<div className="agent-toast"><Check/>{notice}</div>}</main></>}
function App(){const [active,setActive]=useState(pageFromHash);useEffect(()=>{const sync=()=>setActive(pageFromHash());window.addEventListener('hashchange',sync);if(!window.location.hash)window.history.replaceState(null,'',`${window.location.pathname}#/video`);return()=>window.removeEventListener('hashchange',sync)},[]);useEffect(()=>{document.title=`${active==='assets'?'资产管理':active==='video'?'快捷生成视频':pages[active][0]} · ShuLan`},[active]);return <div className={`index-app directory-collapsed ${active==='assets'?'assets-layout':''} ${active==='agent'?'agent-layout':''} ${active==='video'?'video-layout':''}`} style={asCssVariables(lightColors)}><DirectorySidebar active={active} onSelect={id=>window.location.hash=`/${id}`}/>{active==='video'?<VideoWorkspace/>:active==='assets'?<AssetWorkspace/>:active==='agent'?<AgentWorkspace/>:<><PlaceholderPanel/><ContentPage pageId={active}/></>}</div>}
createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>)
